### ISSUE TITLE
Clarity on follow up time

### ISSUE THREAD

**Issue by jdogcoder** [hackclub/slacker#144] opened 2024-02-06 22:08 UTC
@karamassie (and I) would love it if both in elastic, and on the slacker followup message, if it could clearly show if it is 7 or 30 day followup (or other length)

**Comment by grymmy** [comment] 2024-02-15 15:12
Closing this as duplicate of https://github.com/hackclub/slacker/issues/144

**Closed by grymmy** 2024-02-15 15:12 UTC
